# fly.toml app configuration file generated for wb-dating-app on 2023-07-18T21:00:38-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wb-dating-app"
primary_region = "gru"

[build]
  image = "wbolfe/datingapp:latest"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
